### PR TITLE
Add a few area-related wrappers

### PR DESCRIPTION
**Pull request by turboladen**
My first official foray into FFI with Rust, so I may have missed some stuff.

FWIW, I wrote the Ruby gem [ffi-gdal](https://bitbucket.org/agrian/ffi-gdal) (which may or may not be well done, but either way, I've spent hours with the stuff)--I dunno if that could serve as an aid in wrapping some of stuff that's not yet done, but I thought I'd post just in case it helps in some way.

### CODE REVIEW

**Comment by turboladen** [comment]
Hmm... sorry for the ignorance, but I see tests are failing to find the new `gdal-sys` functions: what's the best way to tell `gdal` to use the new stuff?

**Comment by jdroenner** [comment]
Hi, 
thanks for your contribution.

I changed Cargo.toml to use gdal-sys from crates.io for the latest release. I will change it back to use  the sub-crate directly.

**Comment by turboladen** [comment]
@jdroenner sounds good, thanks!

**Comment by jdroenner** [comment]
@turboladen something was wrong with the version string in Cargo.toml. Now gdal-sys from the repository is used again.

**Comment by turboladen** [comment]
@jdroenner aha! Ok, thank you!

**Pull request merged**
